/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface;

/**
 *
 * @author Amouna
 */
import Controller.ClientvalideController;
import Controller.ClientnovalideController;
import edu.esprit.dao.ClientDAO;
import javax.swing.JOptionPane;
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        valider = new javax.swing.JButton();
        listeclient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jTable1.setModel(new ClientnovalideController());
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 530, 140);

        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        jPanel1.add(valider);
        valider.setBounds(90, 310, 90, 40);

        listeclient.setText("Lister Client");
        listeclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeclientActionPerformed(evt);
            }
        });
        jPanel1.add(listeclient);
        listeclient.setBounds(440, 310, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amouna\\Desktop\\admin sys\\desktopwallpapers.org.ua-1398.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, -6, 630, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        ClientDAO cltdao = new ClientDAO();
        if (jTable1.getSelectedRow() != -1) {
            int id = ((Integer) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            
            if (cltdao.ValiderClient(id)) {
                JOptionPane.showMessageDialog(null, "Client valider");
                jTable1 = new javax.swing.JTable();

                jTable1.setModel(new ClientnovalideController());

                jScrollPane1.setViewportView(jTable1);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Aucun client n'a éte selectionneé");
        }
    }//GEN-LAST:event_validerActionPerformed

    private void listeclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeclientActionPerformed
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new ClientvalideController());

        jScrollPane1.setViewportView(jTable1);
        valider.setVisible(false);
    }//GEN-LAST:event_listeclientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listeclient;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
