/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Userinterface;

//import com.toedter.calendar.JCalendar;
import edu.esprit.dao.VendeurDAO;
import edu.esprit.util.MyConnection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import edu.esprit.dao.dealDAO;
import edu.esprit.entities.Vendeur;
import edu.esprit.entities.deal;
import Controller.DealController;
import edu.esprit.dao.CategoriesDAO;
import edu.esprit.dao.dealhistoriqueDAO;
import edu.esprit.entities.Categories;
import edu.esprit.entities.dealhistorique;
import java.awt.event.MouseEvent;
import javax.swing.JComboBox;

/**
 *
 * @author Hamza
 */
public class gestiondeal extends javax.swing.JFrame {

    /**
     * Creates new form Deal
     */
    List<gestiondeal> maliste;// Liste des Deal récupérés
    List<categorie> maliste2;// Liste des categorie récupérés

    public gestiondeal() {
        initComponents();
        setSize(1020,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        qn = new javax.swing.JSpinner();
        ajouter = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        desp = new javax.swing.JTextArea();
        cat = new javax.swing.JComboBox();
        datedebut = new javax.swing.JTextField();
        datefin = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tauxred = new javax.swing.JTextField();
        ven = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Nom:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 120, 30);

        jLabel2.setText("quantite:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 90, 55, 14);

        jLabel3.setText("Date Debut");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 55, 14);

        jLabel4.setText("Date Fin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 170, 55, 14);

        jLabel5.setText("Taux Red");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 210, 55, 14);

        jLabel6.setText("Description");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 380, 55, 14);

        jLabel7.setText("Categorie");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 480, 55, 14);
        getContentPane().add(nom);
        nom.setBounds(60, 20, 230, 30);
        getContentPane().add(qn);
        qn.setBounds(80, 70, 230, 30);

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter);
        ajouter.setBounds(800, 260, 100, 23);

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });
        getContentPane().add(annuler);
        annuler.setBounds(800, 390, 100, 23);

        desp.setColumns(20);
        desp.setRows(5);
        jScrollPane1.setViewportView(desp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 310, 280, 96);

        cat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        getContentPane().add(cat);
        cat.setBounds(150, 480, 153, 20);
        getContentPane().add(datedebut);
        datedebut.setBounds(70, 120, 240, 30);
        getContentPane().add(datefin);
        datefin.setBounds(70, 160, 240, 30);

        jLabel8.setText("vendeur");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 440, 40, 14);
        getContentPane().add(tauxred);
        tauxred.setBounds(80, 200, 130, 30);

        ven.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venActionPerformed(evt);
            }
        });
        getContentPane().add(ven);
        ven.setBounds(140, 440, 115, 20);

        jTable1.setModel(new DealController());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(620, 0, 452, 230);

        modifier.setText("modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier);
        modifier.setBounds(800, 300, 100, 23);

        supprimer.setText("supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(800, 350, 100, 23);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 240, 250, 0);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-50, -10, 1080, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here
        nom.setText("");
        //String quantite="";
        //quantite=qn.getValue().toString();
        //int res = Integer.parseInt(quantite);
        qn.setValue(0);
        datedebut.setText("");
        datefin.setText("");
        tauxred.setText("");
        desp.setText("");
        ven.setSelectedItem("");
        cat.setSelectedItem("");

        //dispose();
    }//GEN-LAST:event_annulerActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        deal deal = new deal();
        VendeurDAO vendeur=new  VendeurDAO();
        CategoriesDAO cata =new CategoriesDAO();
        deal.setNom(nom.getText());
        String quantite = "";
        quantite = qn.getValue().toString();
        int res = Integer.parseInt(quantite);

        deal.setQauntite(res);
        deal.setDatedebut(datedebut.getText());
        deal.setDatefin(datefin.getText());
        deal.setTauxred(Integer.parseInt(tauxred.getText()));
        deal.setDescription(desp.getText());
        deal.setVendeur_id(vendeur.findvendeurBynom((String)ven.getSelectedItem()));
        deal.setCategorie_id(cata.findcatBynom((String)cat.getSelectedItem()));

        dealDAO de = new dealDAO();
        de.insertDeal(deal);
        JOptionPane.showMessageDialog(this, "Ajout effectuée avec succès");
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new DealController());

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);

            }
        });



        jScrollPane2.setViewportView(jTable1);
        nom.setText("");
        datedebut.setText("");
        datefin.setText("");
        tauxred.setText("");
        desp.setText("");
        ven.setSelectedItem("");
        cat.setSelectedItem("");
        qn.setValue(0);



    }//GEN-LAST:event_ajouterActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int a = jTable1.getSelectedRow();
        int id = ((Integer) jTable1.getValueAt(a, 0));
        String Nom = ((String) jTable1.getValueAt(a, 1));
        int quantite = ((Integer) jTable1.getValueAt(a, 2));
        String datedebu = ((String) jTable1.getValueAt(a, 3));
        String datfin = ((String) jTable1.getValueAt(a, 4));
        String des = ((String) jTable1.getValueAt(a, 6));
        String vend = (String) (jTable1.getValueAt(a, 7));
        String cate = ((String) jTable1.getValueAt(a, 9));
       
        nom.setText(Nom);
        qn.getModel().setValue(quantite);
        datedebut.setText(datedebu);
        datefin.setText(datfin);

       tauxred.setText((Integer) jTable1.getValueAt(a, 5)+"");
        desp.setText(des);
        ven.getModel().setSelectedItem(vend);
        cat.getModel().setSelectedItem(cate);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        dealDAO dealDAO = new dealDAO();
        VendeurDAO vendeurDAO = new VendeurDAO();
        List<Vendeur> maliste = new ArrayList<Vendeur>();
        maliste = vendeurDAO.DisplayAllVendeur();
        for (Vendeur v : maliste) {
            ven.addItem(v.getNom());
        }
        CategoriesDAO categoriesDAO = new CategoriesDAO();
        List<Categories> liste = new ArrayList<Categories>();
        liste = categoriesDAO.DisplayAllCategories();
        for (Categories c : liste) {
            cat.addItem(c.getNom());
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        dealDAO dl = new dealDAO();
        VendeurDAO vendeur = new VendeurDAO();
        CategoriesDAO cata = new CategoriesDAO();
        deal d = new deal();
        d.setNom(nom.getText());
        String quantite = "";
        quantite = qn.getValue().toString();
        int res = Integer.parseInt(quantite);

        d.setQauntite(res);
        d.setDatedebut(datedebut.getText());
        d.setDatefin(datefin.getText());
        d.setTauxred(Integer.parseInt(tauxred.getText()));
        d.setDescription(desp.getText());
        d.setVendeur_id(vendeur.findvendeurBynom((String)ven.getSelectedItem()));
        d.setCategorie_id(cata.findcatBynom((String)cat.getSelectedItem()));

        int a = jTable1.getSelectedRow();
        int id = ((Integer) jTable1.getValueAt(a, 0));
        d.setRef(id);

        dl.updateDeal(d);

        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new DealController());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);


        nom.setText("");
        datedebut.setText("");
        datefin.setText("");
        tauxred.setText("");
        desp.setText("");
        ven.setSelectedItem("");
        cat.setSelectedItem("");
        qn.setValue(0);




        // TODO add your handling code here:
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed

        /*dealhistorique dealhis = new dealhistorique();
         
         dealhis.setNom(nom.getText());
         String quantite="";
         quantite=qn.getValue().toString();
         int res = Integer.parseInt(quantite);

         dealhis.setQauntite(res);
         dealhis.setDatedebut(datedebut.getText());
         dealhis.setDatefin(datefin.getText());
         dealhis.setTauxred(Integer.parseInt(tauxred.getText()));
         dealhis.setDescription(desp.getText());
         dealhis.setVendeur((Vendeur) ven.getSelectedItem());
         dealhis.setCategories((Categories)cat.getSelectedItem());
     
         dealhistoriqueDAO de= new dealhistoriqueDAO();
         de.insertDealhis(dealhis);
         JOptionPane.showMessageDialog(this, "Ajout effectuée avec succès");
         jTable1 = new javax.swing.JTable();

         jTable1.setModel(new DealController() );

         jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        
         public void mouseClicked(java.awt.event.MouseEvent evt) {
         jTable1MouseClicked(evt);
             
         }

         });
        
        

         jScrollPane2.setViewportView(jTable1);
         nom.setText("");
         datedebut.setText("");
         datefin.setText("");
         tauxred.setText("");
         desp.setText("");
         ven.setSelectedItem("");
         cat.setSelectedItem("");*/

        int a = jTable1.getSelectedRow();
        int ref = ((Integer) jTable1.getValueAt(a, 0));
        dealDAO d = new dealDAO();

        d.deleteDeal(ref);

        JOptionPane.showMessageDialog(this, "élèment supprimer avec succés  !", "Erreur ", JOptionPane.DEFAULT_OPTION);

        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new DealController());

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jTable1);



        // TODO add your handling code here:
    }//GEN-LAST:event_supprimerActionPerformed

    private void venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestiondeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestiondeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestiondeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestiondeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestiondeal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JComboBox cat;
    private javax.swing.JTextField datedebut;
    private javax.swing.JTextField datefin;
    private javax.swing.JTextArea desp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField nom;
    private javax.swing.JSpinner qn;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField tauxred;
    private javax.swing.JComboBox ven;
    // End of variables declaration//GEN-END:variables
}
